reserve fee as an .env variable
lnbits/lnbits-legend pull request #631
Opened 2022-05-19 11:27 UTC by talvasconcelos

Have the fee reserve as an env variable, defaults to 4000 msats

2022-06-01 11:52 UTC, callebtc requested changes
Great PR! Just some unnecessary changes to clean up, otherwise mergable.

2022-06-01 14:04 UTC, callebtc commented on .env.example
> +LNBITS_FEE_RESERVE=4000 #value in millisats
```suggestion
LNBITS_FEE_RESERVE_MIN=4000 # value in millisats
LNBITS_FEE_RESERVE_PERCENT=1 # value in percent
```

2022-06-01 14:05 UTC, callebtc commented on lnbits/core/services.py
> +    return max(int(RESERVE_FEE), int(amount_msat * 0.01))
```suggestion
    return max(int(RESERVE_FEE), int(amount_msat * LNBITS_FEE_RESERVE_MIN/100.0))
```

2022-06-01 14:05 UTC, callebtc commented on lnbits/settings.py
> +RESERVE_FEE = env.int("LNBITS_RESERVE_FEE", default=4000)
```suggestion
RESERVE_FEE_MIN = env.int("LNBITS_RESERVE_FEE", default=4000)
RESERVE_FEE_PERCENT = env.int("LNBITS_FEE_RESERVE_PERCENT", default=1)
```

2022-06-01 14:08 UTC, callebtc commented
One nitpick: python variable is called `RESERVE_FEE_MIN` and environment variable is `LNBITS_FEE_RESERVE_MIN`

Consistent name like RESERVE_FEE or FEE_RESERVE would be nicer.

2022-06-01 14:56 UTC, callebtc commented on lnbits/settings.py
> +RESERVE_FEE_PERCENT = env.int("LNBITS_RESERVE_FEE_PERCENT", default=1)
```suggestion
RESERVE_FEE_PERCENT = env.float("LNBITS_RESERVE_FEE_PERCENT", default=1)
```

2022-06-01 14:57 UTC, callebtc commented on .env.example
> +LNBITS_RESERVE_FEE_PERCENT=1 # value in percent
```suggestion
LNBITS_RESERVE_FEE_PERCENT=1.0 # value in percent
```

2022-06-03 12:37 UTC, callebtc commented
@talvasconcelos, unfortunately tests are still failing (bleskomat extension?).

2022-08-04 05:35 UTC, callebtc commented
Let's get this PR back out of the grave. Any reason why the default is increased from 2 sat to 4 sat?

2022-08-04 10:14 UTC, talvasconcelos commented
> Let's get this PR back out of the grave. Any reason why the default is increased from 2 sat to 4 sat?

i think it was Ben's call!

2022-08-13 18:04 UTC, callebtc commented on tests/extensions/bleskomat/test_lnurl_api.py
> +    WALLET.pay_invoice.assert_called_once_with(pr, 4000)
```suggestion
    WALLET.pay_invoice.assert_called_once_with(pr, 2000)
```

2022-08-13 18:11 UTC, callebtc commented on .env.example
> +LNBITS_RESERVE_FEE_MIN=4000 # value in millisats
```suggestion
LNBITS_RESERVE_FEE_MIN=2000 # value in millisats
```

2022-08-13 18:14 UTC, callebtc commented on lnbits/settings.py
> +RESERVE_FEE_MIN = env.int("LNBITS_RESERVE_FEE_MIN", default=4000)
```suggestion
RESERVE_FEE_MIN = env.int("LNBITS_RESERVE_FEE_MIN", default=2000)
```

2022-08-13 18:19 UTC, merged